import Foundation

class GMCMInjector {
    static let gamerDesc: [String: String] = [
        "Animated Clothes": "เสื้อผ้าดุ๊กดิ๊กได้ เพิ่มความมีชีวิตชีวาให้ชุดเก่งของคุณ",
        "Animated East Scarp Fish": "ปลาเมือง East Scarp ว่ายน้ำดุ๊กดิ๊กสมจริงขึ้น",
        "Animated Fish": "ปลาว่ายน้ำดุ๊กดิ๊กสมจริงตอนตกปลา",
        "Animated Fish SVE": "ปลาจาก SVE ว่ายน้ำดุ๊กดิ๊กสมจริง",
        "Animated Food and Drinks": "ของกินเครื่องดื่มขยับได้ น่ากินขึ้นเป็นกอง",
        "Animated Furniture and Stuff": "เฟอร์นิเจอร์ขยับได้ ทำให้บ้านดูไม่เงียบเหงา",
        "Animated Ridgeside Village Fish": "ปลาจาก Ridgeside ว่ายน้ำดุ๊กดิ๊กสมจริง",
        "Animated Slime Eggs and Loot": "ไข่สไลม์และไอเทมดรอปขยับได้ ดุ๊กดิ๊กน่ารัก",
        "Automate": "ระบบโรงงานอัตโนมัติ โยนของใส่กล่องแล้วเครื่องทำเองรัวๆ สายอุตสาหกรรมต้องมี",
        "Better Crafting": "ระบบคราฟต์ของที่ฉลาดขึ้น ดึงของจากกล่องมาคราฟต์ได้เลย ไม่ต้องวิ่งหาของให้เหนื่อยหอบ",
        "Button's Extra Trigger Action Stuff": "ส่วนเสริมระบบอีเวนต์เบื้องหลังของม็อดอื่นๆ",
        "CJB Cheats Menu": "เมนูสูตรโกงครอบจักรวาล อยากได้อะไรเสกเอาเลย สายพระเจ้าห้ามพลาด",
        "CJB Item Spawner": "เสกไอเทมได้ทุกอย่างในเกมแบบไร้ขีดจำกัด",
        "Console Commands": "เปิดใช้คำสั่งคอนโซลสำหรับนักพัฒนาม็อด",
        "Content Patcher": "เฟรมเวิร์กหลักที่ใช้ลงม็อดแทบทุกตัวในเกม (ขาดไม่ได้!)",
        "Content Patcher Animations": "ส่วนเสริมให้ Content Patcher รองรับภาพเคลื่อนไหว",
        "Convenient Inventory": "ตัวช่วยจัดระเบียบของ รกแค่ไหนก็เอาอยู่ ย้ายของเข้ากล่องด่วนๆ แบบไวแสง",
        "Custom Companions": "ระบบสัตว์เลี้ยงและเพื่อนร่วมทางแบบ Custom",
        "Deluxe Journal": "สมุดจดคิวงานแบบพรีเมียม จะตั้งเตือนความจำหรือลิสต์งานที่ต้องทำก็มีครบ สายดองงานห้ามพลาด",
        "Downhill Project": "ม็อดเพิ่มพื้นที่และเนื้อเรื่องโปรเจกต์ Downhill",
        "Downhill Project Extras": "ส่วนเสริมสำหรับม็อด Downhill Project",
        "Downhill Project NPCs": "เพิ่มตัวละคร NPC ใหม่จากโปรเจกต์ Downhill",
        "East Scarp: Barber Shop": "ร้านตัดผมที่ East Scarp เปลี่ยนทรงผมได้ตามใจชอบ",
        "East Scarp: C#": "ระบบเบื้องหลังของเมือง East Scarp",
        "East Scarp: Locations": "เพิ่มแผนที่และสถานที่ใหม่ๆ ของเมือง East Scarp",
        "East Scarp: NPCs": "เพิ่มตัวละครหน้าใหม่ในเมือง East Scarp ให้คึกคักกว่าเดิม",
        "Eli & Dylan": "เพิ่มสองหนุ่ม Eli และ Dylan เข้ามาในเมือง",
        "Eli & Dylan- Soot": "เพิ่มสัตว์เลี้ยง Soot ของ Eli และ Dylan",
        "Eli and Dylan Code": "ระบบเบื้องหลังของม็อด Eli & Dylan",
        "Elle's Seasonal Buildings": "เปลี่ยนสไตล์บ้านและสิ่งก่อสร้างให้เข้ากับฤดูกาลแบบสวยๆ",
        "Ellie's Ideal Greenhouse": "ขยายเรือนกระจกให้ใหญ่สะใจ ปลูกของได้เป็นไร่",
        "Farm Type Manager (FTM)": "แอดมินฟาร์มตัวจริง เครื่องมือเสกแร่ สปอว์นมอนสเตอร์ หรือจุดเกิดของป่าได้ดั่งใจ",
        "Forage Settings East Scarp": "จัดการจุดเกิดของป่าในเมือง East Scarp",
        "GI Extra locations - ContentPatcher": "เปิดวาร์ปเกาะจินเจอร์ ขยายพื้นที่ใหม่ๆ ให้เดินเล่นสำรวจกันให้หนำใจ",
        "GI Extra locations - FarmTypeManager": "จัดการจุดเกิดของบนเกาะจินเจอร์ที่ขยายมาใหม่",
        "Generic Mod Config Menu": "เมนูตั้งค่าม็อดในเกมสุดสะดวก (ที่กำลังแปลอยู่นี่ไง!)",
        "Ginger Island Extra Locations - redux": "ตัวหลักสำหรับขยายแผนที่เกาะจินเจอร์",
        "HxW Tilesheets": "ทรัพยากรภาพ Tilesheet สำหรับม็อดอื่นๆ",
        "Immersive Farm 2 Remastered - THAI": "ฟาร์ม IF2R ขนาดใหญ่ยักษ์ เวอร์ชันแปลไทย",
        "Item extensions": "ระบบหลังบ้านสำหรับเพิ่มไอเทมแปลกๆ ใหม่ๆ ที่เกมต้นฉบับไม่มีให้",
        "Leilani": "เพิ่มสาวน้อย Leilani เป็นตัวละครใหม่ในเกม",
        "Livestock Bazaar": "ตลาดนัดค้าขายสัตว์เลี้ยงและปศุสัตว์",
        "Lnh's Peaceful Farm": "แผนที่ฟาร์มสไตล์สงบสุข สวยงามและเล่นสบาย",
        "Lookup Anything": "กด F1 เพื่อดูข้อมูลทุกอย่าง ส่องยันของสวมใส่ยันเวลาเก็บเกี่ยว วิกิเดินได้ชัดๆ",
        "Lumisteria Tilesheets - Indoor": "ภาพของตกแต่งภายในจาก Lumisteria สำหรับสร้างม็อด",
        "Lumisteria Tilesheets - Outdoor": "ภาพสภาพแวดล้อมภายนอกจาก Lumisteria",
        "Mail Framework Mod": "ระบบเบื้องหลังสำหรับจัดการจดหมายในเกม",
        "Mapping Extensions and Extra Properties (MEEP)": "ระบบเบื้องหลังสำหรับสร้างแผนที่ซับซ้อน",
        "Mini Bars": "โชว์หลอดเลือดมอนสเตอร์ตัวเล็กๆ บนหัว จะได้รู้ว่าใกล้ตายรึยัง",
        "MistyCore": "เครื่องมือเบื้องหลัง (Core) สำหรับม็อดอื่นๆ",
        "NPC Map Locations": "โชว์หน้า NPC บนแผนที่ ไม่ต้องวิ่งตามหาตัวให้เหนื่อยหอบอีกต่อไป",
        "Nora The Herpetologist": "เพิ่ม Nora นักสัตว์เลื้อยคลาน เป็นตัวละครใหม่",
        "Part of the Community": "ชาวเมืองจะรับรู้และคุยกันเรื่องที่เราไปทำดี (หรือทำแย่) กับคนอื่น สังคมเกมจะดูสมจริงขึ้น",
        "PortraitsForAll": "ระบบพอร์ตเทรตสำหรับตัวละครทุกตัว",
        "PredictReactionToGift": "ส่องดูว่าถ้าให้ของขวัญชิ้นนี้ NPC จะชอบหรือจะด่า",
        "Quest Helper": "ตัวช่วยบอกใบ้เควส ไม่ต้องงมหาทางเอง",
        "Relocate Buildings And Farm Animals": "ย้ายสิ่งก่อสร้างและสัตว์ในฟาร์มได้อย่างอิสระ",
        "Remapping": "ระบบช่วยตั้งค่าปุ่มกดในเกมใหม่",
        "Ridgeside Village Seasonal Outfits": "แฟชั่นโชว์ตามฤดูกาล จับชาวเมือง Ridgeside มาแต่งตัวใหม่ให้เข้ากับหน้าหนาว หน้าร้อน!",
        "Ridgeside Village [Content Patcher component]": "ทรัพยากรภาพและข้อมูลของ Ridgeside Village",
        "Ridgeside Village [Custom Companions component]": "ระบบสัตว์เลี้ยงและวิญญาณใน Ridgeside",
        "Ridgeside Village [Farm Type Manager component]": "จุดเกิดของป่าและมอนสเตอร์ใน Ridgeside",
        "Ridgeside Village [SMAPI component]": "ระบบเบื้องหลังหลักของเมือง Ridgeside Village (เมืองใหญ่อลังการ!)",
        "Save Backup": "ระบบสำรองไฟล์เซฟอัตโนมัติ กันเซฟพัง น้ำตาจะได้ไม่เช็ดหัวเข่า",
        "Seasonal Mariner to Mermaid": "เปลี่ยนคนขายจี้หอยนางรมให้เป็นนางเงือกตามฤดูกาล",
        "SinZational Speedy Solutions": "เครื่องมือช่วยเร่งสปีดตัวเกมสำหรับนักพัฒนาม็อด",
        "Sitting Restores Energy": "ระบบนั่งพักฟื้นพลังงาน นั่งเก้าอี้แล้วหลอดเด้ง ไม่ต้องรีบกลับไปนอน",
        "Skip or Socialize": "ระบบข้ามหรือดูคัทซีนอีเวนต์แบบเลือกได้ตามใจ",
        "Social Page Order Redux": "จัดเรียงลำดับ NPC ในหน้าความสัมพันธ์ใหม่ให้ดูง่ายขึ้น",
        "SpaceCore": "เฟรมเวิร์กหลักที่ม็อดเทพๆ หลายตัวต้องใช้",
        "Standardized Seed Sprites": "ปรับภาพเมล็ดพันธุ์ให้ดูสมจริงและเป็นมาตรฐานเดียวกัน",
        "Stardew Valley - THAI": "ม็อดแปลภาษาไทยหลักของเกม Stardew Valley (ฝีมือคนไทย!)",
        "Stardew Valley Expanded": "ม็อดขยายจักรวาลเกม เพิ่มเมือง ตัวละคร และเนื้อเรื่องระดับ DLC ยักษ์",
        "Stardew Valley Expanded Farm Type Manager": "ระบบจัดการของป่าและมอนสเตอร์สำหรับ SVE",
        "Stardew Valley Expanded Forage Locations - Immersive Farm 2": "ระบบของป่าสำหรับแผนที่ IF2R",
        "StardewHack": "ม็อดพ่อทุกสถาบัน เฟรมเวิร์กสุดเทพที่ช่วยให้ม็อดอื่นๆ แฮกเข้าระบบเกมได้สบายๆ",
        "StardewUI": "ระบบแสดงผล UI เบื้องหลังสำหรับม็อด",
        "Sword & Sorcery [CP]": "ภาพและข้อมูลของม็อดดาบและเวทมนตร์",
        "Sword and Sorcery (SMAPI Component)": "ระบบเบื้องหลังม็อดดาบและเวทมนตร์",
        "TDIT - Portraits for Extras": "เพิ่มรูปพอร์ตเทรตสวยๆ ให้พวกตัวประกอบ จะได้ดูมีชีวิตชีวาไม่เป็นแค่อากาศธาตุอีกต่อไป",
        "Thai Font Adjuster": "ตัวปรับแต่งฟอนต์ภาษาไทยให้สวยและอ่านง่าย",
        "Tidy Pam": "ทำความสะอาดหน้าบ้านให้ Pam ดูเป็นระเบียบขึ้น",
        "Tiny Totem Statue Obelisks": "ย่อส่วนเสาวาร์ปอันเบ้อเริ่มให้กลายเป็นรูปปั้นจิ๋ว ประหยัดที่ในฟาร์มแถมดูมินิมอลสุดๆ",
        "Tractor Mod": "รถไถซิ่งประจำฟาร์ม! กวาดเรียบทั้งเกี่ยวข้าว รดน้ำ ทุบหิน สายทำฟาร์มสเกลใหญ่ต้องมี",
        "TrinketTinker": "ปรับแต่งเครื่องรางและน้องๆ สัตว์เลี้ยงตามติดได้แบบอิสระ สายแฟชั่นต้องจัด",
        "UI Info Suite 2 Alternative": "โชว์ข้อมูลทุกอย่างแบบหมดเปลือก ตั้งแต่วันเกิดยันระยะสปริงเกลอร์ ไม่ต้องเปิดวิกิให้เมื่อย",
        "Unlockable Bundles": "เพิ่ม Bundle ศาลาว่าการแบบใหม่ๆ สายฟาร์มของทำเควสเตรียมตัวเหนื่อยได้เลย!",
        "Wear More Rings": "ใครว่าใส่แหวนได้แค่สองวง? ม็อดนี้จัดให้ ใส่แหวนได้สิบนิ้ว เอาให้บัฟทะลุหลอดไปเลย",
        "World Navigator": "Google Maps ประจำเมือง Pelican ค้นหา NPC และสถานที่ได้เป๊ะๆ ไม่มีหลงทางแน่นอน",
        "[CP] Additional Farm Cave": "ถ้ำใหม่ในฟาร์ม ขยายพื้นที่ให้กว้างขึ้น เอาไว้ดองของหรือทำฟาร์มเห็ดก็แจ่ม",
        "[CP] Skip or Socialize": "ทรัพยากรภาพของม็อด Skip or Socialize",
        "[FTM] Additional Farm Cave": "ระบบจุดเกิดเห็ดและแร่ในถ้ำใหม่"
    ]
    
    static let normalDesc: [String: String] = [
        "Animated Clothes": "เพิ่มภาพเคลื่อนไหวให้กับเสื้อผ้า",
        "Animated East Scarp Fish": "เพิ่มภาพเคลื่อนไหวให้กับปลาในม็อด East Scarp",
        "Animated Fish": "เพิ่มภาพเคลื่อนไหวให้กับปลาขณะตกปลา",
        "Animated Fish SVE": "เพิ่มภาพเคลื่อนไหวให้กับปลาในม็อด Stardew Valley Expanded",
        "Animated Food and Drinks": "เพิ่มภาพเคลื่อนไหวให้กับไอเทมประเภทอาหารและเครื่องดื่ม",
        "Animated Furniture and Stuff": "เพิ่มภาพเคลื่อนไหวให้กับเฟอร์นิเจอร์และของตกแต่ง",
        "Animated Ridgeside Village Fish": "เพิ่มภาพเคลื่อนไหวให้กับปลาในม็อด Ridgeside Village",
        "Animated Slime Eggs and Loot": "เพิ่มภาพเคลื่อนไหวให้กับไข่สไลม์และไอเทมดรอป",
        "Automate": "ระบบทำงานอัตโนมัติสำหรับเครื่องจักรและกล่องเก็บของ",
        "Better Crafting": "ปรับปรุงระบบและหน้าต่างการสร้างไอเทมให้ใช้งานง่ายขึ้น",
        "Button's Extra Trigger Action Stuff": "ส่วนเสริมระบบอีเวนต์สำหรับม็อดต่างๆ",
        "CJB Cheats Menu": "เมนูสำหรับปรับแต่งการตั้งค่าและช่วยเหลือการเล่นเกม",
        "CJB Item Spawner": "เมนูสำหรับเสกไอเทมทุกชนิดภายในเกม",
        "Console Commands": "เพิ่มคำสั่งคอนโซลเพิ่มเติมสำหรับนักพัฒนาม็อด",
        "Content Patcher": "เฟรมเวิร์กหลักที่ใช้สำหรับการติดตั้งและรันม็อดต่างๆ",
        "Content Patcher Animations": "ส่วนเสริมให้ Content Patcher รองรับการทำงานของภาพเคลื่อนไหว",
        "Convenient Inventory": "ปรับปรุงระบบช่องเก็บของเพื่อการจัดระเบียบที่สะดวกรวดเร็ว",
        "Custom Companions": "ระบบเพิ่มสัตว์เลี้ยงและเพื่อนร่วมทางแบบปรับแต่งเองได้",
        "Deluxe Journal": "เพิ่มสมุดบันทึกขั้นสูงสำหรับจัดการภารกิจและการแจ้งเตือน",
        "Downhill Project": "ม็อดขยายพื้นที่และเพิ่มเนื้อเรื่องในโปรเจกต์ Downhill",
        "Downhill Project Extras": "ม็อดเสริมสำหรับโปรเจกต์ Downhill",
        "Downhill Project NPCs": "เพิ่มตัวละคร NPC ใหม่สำหรับโปรเจกต์ Downhill",
        "East Scarp: Barber Shop": "เพิ่มสถานที่ร้านตัดผมภายในเมือง East Scarp",
        "East Scarp: C#": "ระบบเบื้องหลังสำหรับรันม็อด East Scarp",
        "East Scarp: Locations": "เพิ่มแผนที่และสถานที่ใหม่สำหรับม็อด East Scarp",
        "East Scarp: NPCs": "เพิ่มตัวละครใหม่สำหรับม็อด East Scarp",
        "Eli & Dylan": "ม็อดเพิ่มตัวละครใหม่ Eli และ Dylan",
        "Eli & Dylan- Soot": "เพิ่มสัตว์เลี้ยง Soot สำหรับม็อด Eli & Dylan",
        "Eli and Dylan Code": "ระบบเบื้องหลังสำหรับรันม็อด Eli & Dylan",
        "Elle's Seasonal Buildings": "ปรับแต่งรูปลักษณ์ของสิ่งก่อสร้างให้เปลี่ยนไปตามฤดูกาล",
        "Ellie's Ideal Greenhouse": "ขยายขนาดและปรับปรุงรูปแบบของเรือนกระจก",
        "Farm Type Manager (FTM)": "เครื่องมือสำหรับจัดการจุดเกิดของไอเทม แร่ และมอนสเตอร์",
        "Forage Settings East Scarp": "การตั้งค่าจุดเกิดของป่าสำหรับม็อด East Scarp",
        "GI Extra locations - ContentPatcher": "ส่วนเสริม Content Patcher สำหรับเพิ่มพื้นที่บนเกาะจินเจอร์",
        "GI Extra locations - FarmTypeManager": "ส่วนเสริมจุดเกิดของป่าสำหรับพื้นที่ใหม่บนเกาะจินเจอร์",
        "Generic Mod Config Menu": "เมนูตั้งค่าสำหรับม็อดต่างๆ ในเกม",
        "Ginger Island Extra Locations - redux": "ม็อดหลักสำหรับเพิ่มพื้นที่และสถานที่บนเกาะจินเจอร์",
        "HxW Tilesheets": "ทรัพยากรภาพและชุดกระเบื้องสำหรับใช้งานกับม็อดอื่นๆ",
        "Immersive Farm 2 Remastered - THAI": "แผนที่ฟาร์ม Immersive Farm 2 (แปลภาษาไทย)",
        "Item extensions": "ระบบขยายความสามารถในการเพิ่มไอเทมสำหรับนักพัฒนาม็อด",
        "Leilani": "ม็อดเพิ่มตัวละครใหม่ Leilani",
        "Livestock Bazaar": "เพิ่มระบบตลาดค้าขายและสัตว์เลี้ยงแบบใหม่",
        "Lnh's Peaceful Farm": "แผนที่ฟาร์มสไตล์เงียบสงบเน้นความสวยงาม",
        "Lookup Anything": "แสดงข้อมูลโดยละเอียดของไอเทมและตัวละครเมื่อกด F1",
        "Lumisteria Tilesheets - Indoor": "ภาพชุดกระเบื้องสำหรับตกแต่งภายใน",
        "Lumisteria Tilesheets - Outdoor": "ภาพชุดกระเบื้องสำหรับตกแต่งภายนอก",
        "Mail Framework Mod": "ระบบเบื้องหลังสำหรับจัดการและเพิ่มจดหมาย",
        "Mapping Extensions and Extra Properties (MEEP)": "ระบบเบื้องหลังสำหรับสร้างและจัดการแผนที่ที่ซับซ้อน",
        "Mini Bars": "เพิ่มหลอดพลังชีวิตบนตัวมอนสเตอร์",
        "MistyCore": "เครื่องมือเบื้องหลัง (Core) สำหรับจัดการม็อด",
        "NPC Map Locations": "แสดงตำแหน่งแบบเรียลไทม์ของตัวละครบนแผนที่",
        "Nora The Herpetologist": "ม็อดเพิ่มตัวละครใหม่ Nora",
        "Part of the Community": "เพิ่มระบบปฏิสัมพันธ์และการรับรู้ของสังคมชาวเมือง",
        "PortraitsForAll": "ระบบจัดการภาพพอร์ตเทรตสำหรับตัวละครทุกตัว",
        "PredictReactionToGift": "แสดงการทำนายว่าตัวละครจะชอบของขวัญชิ้นนั้นหรือไม่",
        "Quest Helper": "เครื่องมือช่วยเหลือและให้คำแนะนำสำหรับภารกิจ",
        "Relocate Buildings And Farm Animals": "ระบบสำหรับเคลื่อนย้ายสิ่งก่อสร้างและสัตว์ในฟาร์ม",
        "Remapping": "ระบบปรับเปลี่ยนและตั้งค่าการควบคุมปุ่มกด",
        "Ridgeside Village Seasonal Outfits": "เพิ่มชุดแต่งกายตามฤดูกาลสำหรับตัวละครใน Ridgeside Village",
        "Ridgeside Village [Content Patcher component]": "ทรัพยากรและเนื้อหาสำหรับม็อด Ridgeside Village",
        "Ridgeside Village [Custom Companions component]": "ระบบสัตว์เลี้ยงเสริมสำหรับม็อด Ridgeside Village",
        "Ridgeside Village [Farm Type Manager component]": "ระบบจัดการจุดเกิดและมอนสเตอร์สำหรับ Ridgeside Village",
        "Ridgeside Village [SMAPI component]": "ระบบเบื้องหลังสำหรับม็อด Ridgeside Village",
        "Save Backup": "ระบบสำรองไฟล์เซฟเกมอัตโนมัติ",
        "Seasonal Mariner to Mermaid": "เปลี่ยนตัวละครขายจี้หอยนางรมเป็นนางเงือกตามฤดูกาล",
        "SinZational Speedy Solutions": "เครื่องมือเพื่อเพิ่มประสิทธิภาพเกมสำหรับนักพัฒนาม็อด",
        "Sitting Restores Energy": "ระบบฟื้นฟูพลังงานเมื่อตัวละครนั่งพัก",
        "Skip or Socialize": "ระบบข้ามคัทซีนเหตุการณ์ หรือเลือกเข้าร่วมเหตุการณ์ได้",
        "Social Page Order Redux": "ปรับปรุงการจัดเรียงลำดับตัวละครในหน้าต่างสังคม",
        "SpaceCore": "เฟรมเวิร์กหลักที่จำเป็นสำหรับการรันม็อดต่างๆ",
        "Standardized Seed Sprites": "ปรับภาพลักษณ์ของเมล็ดพันธุ์ให้เป็นมาตรฐานเดียวกัน",
        "Stardew Valley - THAI": "ม็อดแปลภาษาไทยหลักสำหรับเกม Stardew Valley",
        "Stardew Valley Expanded": "ม็อดขยายเนื้อหา เพิ่มพื้นที่ ตัวละคร และเหตุการณ์ใหม่",
        "Stardew Valley Expanded Farm Type Manager": "ระบบจัดการจุดเกิดของป่าและมอนสเตอร์สำหรับ SVE",
        "Stardew Valley Expanded Forage Locations - Immersive Farm 2": "ระบบจัดการของป่าสำหรับแผนที่ IF2R",
        "StardewHack": "เฟรมเวิร์กหลักสำหรับระบบม็อดเชิงลึก",
        "StardewUI": "ระบบเบื้องหลังสำหรับการแสดงผลอินเทอร์เฟซผู้ใช้",
        "Sword & Sorcery [CP]": "ภาพเนื้อหาสำหรับม็อดดาบและเวทมนตร์",
        "Sword and Sorcery (SMAPI Component)": "ระบบเบื้องหลังสำหรับม็อดดาบและเวทมนตร์",
        "TDIT - Portraits for Extras": "เพิ่มภาพพอร์ตเทรตสำหรับตัวละครประกอบและตัวละครทั่วไป",
        "Thai Font Adjuster": "เครื่องมือปรับแต่งตัวอักษรภาษาไทย",
        "Tidy Pam": "ปรับปรุงบริเวณลานหน้าบ้านของ Pam ให้ดูเป็นระเบียบ",
        "Tiny Totem Statue Obelisks": "ย่อขนาดเสาวาร์ปให้กลายเป็นรูปปั้นขนาดเล็ก",
        "Tractor Mod": "เพิ่มรถแทรกเตอร์สำหรับช่วยทุ่นแรงในการทำฟาร์ม",
        "TrinketTinker": "ระบบปรับแต่งและตั้งค่าเครื่องรางและสัตว์เลี้ยงติดตัว",
        "UI Info Suite 2 Alternative": "เพิ่มการแสดงข้อมูลที่เป็นประโยชน์ เช่น วันเกิด ระยะสปริงเกลอร์ และอื่นๆ",
        "Unlockable Bundles": "เพิ่มแพ็กเกจ Bundle ใหม่สำหรับศูนย์ชุมชน",
        "Wear More Rings": "เพิ่มจำนวนช่องสวมใส่แหวนให้ตัวละคร",
        "World Navigator": "ระบบค้นหาและนำทางไปยังสถานที่และตัวละครต่างๆ",
        "[CP] Additional Farm Cave": "เพิ่มพื้นที่และส่วนขยายของถ้ำภายในฟาร์ม",
        "[CP] Skip or Socialize": "ทรัพยากรภาพสำหรับม็อด Skip or Socialize",
        "[FTM] Additional Farm Cave": "ระบบจุดเกิดเห็ดและแร่สำหรับถ้ำภายในฟาร์ม"
    ]
}
